apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inkpot-web-deployment
  name: inkpot-web-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inkpot-web-deployment
  template:
    metadata:
      labels:
        app: inkpot-web-deployment
    spec:
      containers:
      - image: eu.gcr.io/PROJECT_ID/IMAGE:TAG
        name: inkpot-web-deployment
        resources:
          limits:
            cpu: 20m
          requests:
            cpu: 10m
        ports:
        - containerPort: 80
          protocol: TCP
