apiVersion: v1
kind: Service
metadata:
  name: inkpot-web
  labels:
    app: inkpot-web-deployment
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: inkpot-web-deployment